spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

addon:
  key: tag
  base-url: https://48932c0924ce.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG
spring.thymeleaf.cache: false