spring.jpa.hibernate.ddl-auto: none
spring.datasource.url: jdbc:hsqldb:file:addon-db # Use a file-based backing store for HSQL

addon:
  key: tag
  base-url: https://fa0788224f79.ngrok.io

logging.level.com.atlassian.connect.spring: DEBUG
spring.thymeleaf.cache: false